import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { colorRgb, colors } from "../lib/colors";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const css = `/* Generated by npm run gen:colors — do not edit; source: lib/colors.ts */
:root {
  /* Brand */
  --qt-brand: ${colors.brand.DEFAULT};
  --qt-brand-dark: ${colors.brand.dark};
  --qt-brand-light: ${colors.brand.light};
  --qt-brand-mid: ${colors.brand.mid};
  --qt-brand-dark-card: ${colors.brand.darkCard};
  --qt-brand-soft: ${colors.cream.light};
  --qt-brand-text: ${colors.ink};
  --qt-brand-rgb: ${colorRgb.brand};

  /* Cream & surfaces */
  --qt-cream: ${colors.cream.DEFAULT};
  --qt-cream-light: ${colors.cream.light};
  --qt-cream-on-dark: ${colors.cream.onDark};
  --qt-cream-on-dark-rgb: ${colorRgb.creamOnDark};
  --qt-accent: ${colors.cream.onDark};
  --qt-accent-dark: ${colors.cream.accentDark};
  --qt-accent-rgb: ${colorRgb.creamOnDark};
  --qt-surface: ${colors.cream.DEFAULT};
  --qt-card: ${colors.card};

  /* Text */
  --qt-ink: ${colors.ink};
  --qt-muted: ${colors.muted.DEFAULT};
  --qt-dark: ${colors.brand.DEFAULT};
  --qt-dark-card: ${colors.brand.darkCard};

  /* Actions */
  --qt-primary-bg: ${colors.brand.DEFAULT};
  --qt-primary-text: ${colors.cream.onDark};
  --qt-primary-hover: ${colors.brand.dark};
  --qt-primary-rgb: ${colorRgb.brand};

  /* App shell (shadcn / dashboard) */
  --radius: 0.75rem;
  --background: var(--qt-cream);
  --foreground: var(--qt-ink);
  --card: var(--qt-card);
  --card-foreground: var(--qt-ink);
  --popover: var(--qt-card);
  --popover-foreground: var(--qt-ink);
  --primary: var(--qt-brand);
  --primary-foreground: var(--qt-cream-on-dark);
  --secondary: var(--qt-cream-light);
  --secondary-foreground: var(--qt-ink);
  --muted: var(--qt-cream-light);
  --muted-foreground: var(--qt-muted);
  --accent: ${colors.cream.uiAccent};
  --accent-foreground: var(--qt-ink);
  --destructive: ${colors.destructive};
  --border: ${colors.border};
  --input: ${colors.border};
  --ring: var(--qt-brand);
  --sidebar: var(--qt-brand);
  --sidebar-foreground: var(--qt-cream-on-dark);
  --sidebar-muted: ${colors.muted.sidebar};
  --sidebar-active: var(--qt-brand-light);
  --success: ${colors.success};
  --warning: ${colors.warning};
  --shadow-card: 0 1px 3px 0 rgb(var(--qt-brand-rgb) / 0.06), 0 1px 2px -1px rgb(var(--qt-brand-rgb) / 0.06);
  --shadow-md: 0 4px 6px -1px rgb(var(--qt-brand-rgb) / 0.08), 0 2px 4px -2px rgb(var(--qt-brand-rgb) / 0.05);
}
`;

writeFileSync(join(root, "app/brand-tokens.css"), css);
console.log("Generated app/brand-tokens.css from lib/colors.ts");
